sudo: required
dist: trusty
language: python

python:
  - "2.7"
  - "3.5"

install:
  - TEST_DIR=$PWD
  - pip install --upgrade pip setuptools wheel
  - pip install coveralls
  - pip install nose
  - pip install --only-binary=numpy,scipy,pandas -r requirements.txt

script:
  - nosetests tests
  - coveralls
