sudo: required
dist: trusty
language: python
services:
  - mongodb
  - redis-server

cache: pip


python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"

install:
  - TEST_DIR=$PWD
  - pip install --upgrade pip setuptools wheel
  - pip install coverage nose rednose
  - pip install --only-binary=numpy,scipy,pandas -r requirements.txt

before_script:
  - mongo mydb_test --eval 'db.createUser({user:"travis",pwd:"test",roles:["readWrite"]});'

script:
  - nosetests tests
  - coveralls

