sudo: required
dist: trusty
language: python
services:
  - mongodb
  - redis-server

cache:
    directories:
        - $HOME/.cache/pip

python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"

install:
  - pip install -U pip wheel
  - pip install --requirement=$TRAVIS_BUILD_DIR/requirements.txt
  - pip install coveralls nose rednose

before_script:
  - mongo mydb_test --eval 'db.createUser({user:"travis",pwd:"test",roles:["readWrite"]});'

script:
  - nosetests tests
  - coveralls

